.MODEL SMALL
.STACK 100H
.DATA
NUM DB 0,0,1,0,0,1,1,0
DECIMAL DB ?
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS, AX
    
    MOV CX, 08H    ;FOR 1 BYTE=8 BIT
    XOR AX,AX
L1:
    SHL AL,1
    MOV BL,[SI]
    ADD AL,BL
    INC SI
    LOOP L1
    
    MOV DECIMAL, AL
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN