.MODEL SMALL
.STACK 100H
.DATA 
ARR DB 4,3,3,3,3,2,2,2,1
N DB 9
M_O DB 0H                 ;NUMBER OF TERMS IN THE ARRAY 
Mode DB ?
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS, AX
    
    XOR CX,CX
    MOV CL, N
    DEC CL
    XOR BX,BX            ;DX AND BX REGISTER IS CLEARED, BL WILL KEEP THE COUNT
    XOR DX,DX            ;AND DL WILL KEEP THE NUMBER THAT IS BEING COUNTED
    XOR AX,AX            ;AX WILL KEEP THE SI VALUE OF THE NUMBER WHICH OCCURED MOST
    MOV SI,CX
COUNT:
    CMP [ARR+SI], DL
    JE EQL
UNEQL:
    MOV BL, 1H
    MOV DL, [ARR+SI]
    CMP M_O, BL
    JL CHANGE_SI
    CMP SI, 0H
    JE EXIT
    DEC SI
    JMP COUNT
    
EQL:
    INC BL   
    CMP M_O, BL
    JL CHANGE_SI
    DEC SI
    JMP COUNT
CHANGE_SI:
    MOV M_O, BL
    MOV AX,SI
    DEC SI
    JMP COUNT
    
    
    EXIT:
    MOV SI, AX
    MOV AL, [ARR+SI] 
    MOV MODE, AL
    MOV AH,4CH
    INT 21H
END MAIN